assessment_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:task_id>/details", views.details, name="details"),
    path("add", views.add, name="add"),
    path("clear", views.clear, name="clear"),
    path("<int:task_id>/", views.edit, name="edit"),
    path("<int:task_id>/delete", views.delete, name="delete"),
    path("<int:task_id>/complete", views.complete, name="complete"),
    path("<int:location_id>/get_weather", views.get_weather, name="get_weather"),
    path("weather_refresh", views.force_weather_refresh, name="force_weather_refresh"),
]

todolist/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Model for todolist item
class Task(models.Model):
    name = models.CharField(max_length=500)
    date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)
    done = models.BooleanField(default=False)
    location = models.ForeignKey(
        'Location', on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return self.name


# Model for Location
class Location(models.Model):
    name = models.CharField(max_length=500)
    lat = models.FloatField(validators=[MinValueValidator(-90), MaxValueValidator(90)])
    lon = models.FloatField(validators=[MinValueValidator(-180), MaxValueValidator(180)])

    def __str__(self):
        return self.name


# Model for Weather
class Weather(models.Model):
    # When the location for the weather read is deleted, the read is obsolete and should be deleted along
    location = models.OneToOneField(
        'Location', on_delete=models.CASCADE, primary_key=True, related_name='weather'
    )
    temperature = models.FloatField()
    status = models.CharField(max_length=500)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.status + ', ' + str(self.temperature)


# Model for last weather reads of Done Tasks
class LastWeatherRead(models.Model):
    task = models.OneToOneField(
        'Task', on_delete=models.CASCADE, primary_key=True, related_name='last_weather_read'
    )
    temperature = models.FloatField()
    status = models.CharField(max_length=500)

todolist/forms.py
from django import forms
from .models import Task, Location


# Form for Task
class TaskForm(forms.ModelForm):
    date = forms.SplitDateTimeField(
        widget=forms.SplitDateTimeWidget(date_attrs={'type': 'date'}, time_attrs={'type': 'time'})
    )
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'onChange': 'getWeatherForLocation(this.value)'
            }
        ),
        empty_label="No location",
        required=False,
        blank=True,
    )

    class Meta:
        model = Task
        fields = ['name', 'date', 'location']

todolist/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from todolist.forms import TaskForm
from todolist.models import Task, Weather, Location, LastWeatherRead
from todolist.weather import fetch_weather


# Endpoint for listing all tasks
def index(request):
    tasks = Task.objects.order_by('date')
    # Get weather data for active locations
    active_locations = tasks.exclude(done=True).values('location').distinct()
    locations = Location.objects.filter(id__in=active_locations)
    weather_reads = {}
    for location in locations:
        weather_reads[location.id] = fetch_weather(location)
    # Expand tasks with weather information
    for task in tasks:
        if task.done and hasattr(task, 'last_weather_read'):
            task.weather = {
                'temp': task.last_weather_read.temperature,
                'weather': task.last_weather_read.status
            }
        elif task.location is not None:
            task.weather = weather_reads[task.location.id]

    return render(
        request,
        "tasks/index.html",
        {'tasks': tasks}
    )


# Endpoint for task details
def details(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    # Fetch weather for the task location
    if task.location is not None:
        weather = fetch_weather(task.location)
    else:
        weather = None
    return render(request, "tasks/details.html", {'task': task, "weather": weather})


# Endpoint for adding new tasks
def add(request):
    # process form data if this is a POST
    if request.method == "POST":
        # create form and complete with request data
        form = TaskForm(request.POST)
        # validate
        if form.is_valid():
            # Save new Task
            form.save()
            # redirect to index:
            return HttpResponseRedirect("/")

    # display blank form if not a POST
    else:
        form = TaskForm()

    return render(request, "tasks/add.html", {"form": form})


# Endpoint for clearing the entire list of tasks
def clear(request):
    if request.method == "POST":
        entries = Task.objects.all()
        entries.delete()

    return HttpResponseRedirect("/")


# Endpoint for editing existing tasks
def edit(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    # Fetch weather for the task location
    if task.location is not None:
        weather = fetch_weather(task.location)
    else:
        weather = None
    form = TaskForm(request.POST or None, instance=task)
    # process form data if this is a POST
    if request.method == "POST" and form.is_valid() and form.has_changed():
        # save existing Task
        form.save()
        # redirect to index:
        return HttpResponseRedirect("/")
    if not form.has_changed():
        form.add_error(None, 'Nothing changed')

    return render(request, "tasks/edit.html", {"form": form, "task": task, "weather": weather})


# Endpoint for deleting existing tasks
def delete(request, task_id):
    if request.method == "POST":
        # fetch Task to be deleted
        task = get_object_or_404(Task, pk=task_id)
        # delete existing Task
        task.delete()

    # redirect to index:
    return HttpResponseRedirect("/")


# Endpoint for marking an existing task as done
def complete(request, task_id):
    if request.method == "POST":
        # fetch Task to be updated
        task = get_object_or_404(Task, pk=task_id)
        # update Task
        task.done = True
        if hasattr(task, 'location'):
            # Save the last weather read for the task, it won't be fetching weather updates anymore
            last_weather_read = Weather.objects.filter(location=task.location).first()
            if last_weather_read:
                LastWeatherRead.objects.create(
                    task=task,
                    temperature=last_weather_read.temperature,
                    status=last_weather_read.status
                )

        task.save()

    # redirect to index:
    return HttpResponseRedirect("/")


# Endpoint for fetching weather for fetch API calls
def get_weather(request, location_id):
    location = get_object_or_404(Location, pk=location_id)
    data = fetch_weather(location)

    return JsonResponse(data)


# Endpoint for clearing all weather data to force it to be re-fetched
def force_weather_refresh(request):
    if request.method == "POST":
        entries = Weather.objects.all()
        entries.delete()

    return HttpResponseRedirect("/")

todolist/templates/tasks/add.html
{% extends "tasks/base.html" %}
{% load static %}
{% block content %}

<div class="background">
    <form action="{% url 'todolist:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    {% include "tasks/temperature.html" %}
</div>
{% include "tasks/goback.html" %}
<script src="{% static 'js/get_weather.js' %}"></script>
{% endblock %}

todolist/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link  href="{% static 'css/styles.css' %}" rel="stylesheet">
  <title>My TODO App</title>
</head>
<body>
  <header>
  </header>

  <main>
    {% block content %}
    {% endblock content %}
  </main>
</body>
</html>

todolist/templates/tasks/details.html
{% extends "tasks/base.html" %}

{% block content %}

<div class="background{% if weather.weather %} {{ weather.weather }}{% endif %}">
    <div class="grid-container">
        <div class="grid-item">What: </div>
        <div class="grid-item">{{ task.name }}</div>
        <div class="grid-item">When: </div>
        <div class="grid-item">{{ task.date }}</div>
        <div class="grid-item">Done? </div>
        <div class="grid-item">{% if task.done %}Yes{% else %}No{% endif %}</div>
    </div>
    <button value='Edit'><a href="{% url 'todolist:edit' task.id %}">Edit</a></button>
    <form action="{% url 'todolist:delete' task.id  %}" method="post">
        {% csrf_token %}
        <button type='submit' value='Delete'>Delete</button>
    </form>
    <form action="{% url 'todolist:complete' task.id %}" method="post">
        {% csrf_token %}
        <button type='submit' value='Complete'>Mark as DONE</button>
    </form>
</div>
{% include "tasks/goback.html" %}
{% endblock %}

todolist/templates/tasks/edit.html
{% extends "tasks/base.html" %}
{% load static %}
{% block content %}

<div class="background{% if weather.weather %} {{ weather.weather }}{% endif %}">
    <form action="{% url 'todolist:edit' task.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    {% include "tasks/temperature.html" %}
    <form action="{% url 'todolist:delete' task.id  %}" method="post">
        {% csrf_token %}
        <button type='submit' value='Delete'>Delete</button>
    </form>
</div>
{% include "tasks/goback.html" %}
<script src="{% static 'js/get_weather.js' %}"></script>
{% endblock %}

todolist/templates/tasks/goback.html
<div class="footer">
    <button>
        <a href="{% url 'todolist:index' %}">
            Go to list
        </a>
    </button>
</div>

todolist/templates/tasks/index.html
{% extends "tasks/base.html" %}
{% block content %}
<h2>Tasks TODO list</h2>
<table>
    <tr>
    <th>What</th>
    <th>When</th>
    <th>Done?</th>
    </tr>
    {% for task in tasks %}
        <tr>
            <td>
                <div class="background {{ task.weather.weather }}">
                    <a href="{% url 'todolist:details' task.id %}">{{ task.name }}</a>
                </div>
            </td>
            <td>{{ task.date|date:"H:i, l, jS F, Y" }}</td>
            {% if task.done %}
                <td>DONE!</td>
            {% else %}
                <td>
                    <form action="{% url 'todolist:complete' task.id %}" method="post">
                        {% csrf_token %}
                        <button type='submit' value='Complete'>Mark as DONE</button>
                    </form>
                </td>
            {% endif %}
        </tr>
    {% empty %}
        <tr>
            <td colspan="2">Nothing to do!</td>
        </tr>
    {% endfor %}
</table>
<button>
    <a href="{% url 'todolist:add' %}">
        Add new Task
    </a>
</button>
<form action="{% url 'todolist:clear' %}" method="post">
    {% csrf_token %}
    <button type='submit' value='Clear'>Restart TODO list</button>
</form>
<form action="{% url 'todolist:force_weather_refresh' %}" method="post">
    {% csrf_token %}
    <button type='submit' value='Refresh'>Refresh weather readings</button>
</form>
{% endblock %}

todolist/templates/tasks/temperature.html
<div class="temperature">
    Current temperature for this location:
    <span class="temp_read">{% if weather.temp %}{{ weather.temp }}{% else %}--{% endif %}</span>
</div>